oauth:
  kakao:
    rest-api-key: ENC(mulQBCl2Wl58huvJFH1hrgssYz6XaDG9EFIdCeltjjADafMYVodvB0t8dU8vt5NR)

---

spring:
  profiles:
    active: development

---

spring:
  profiles:
    active: prod

---

spring:
  profiles:
    active: local